# Netlify configuration for FairFence - Frontend Only
# Backend API routes are handled by Supabase Edge Functions

[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

# SPA routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
