# Netlify Configuration for FairFence Contracting App

[build]
  # Use the correct build command from package.json
  command = "npm run build"

  # Publish the built frontend assets
  publish = "dist/public"

  # Set Node version
  environment = { NODE_VERSION = "20" }

# Redirect API requests to the Express server
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# SPA fallback - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
